use_frameworks!

platform :ios, '8.0'

target 'BQBaseComponent_Example' do
  pod 'BQBaseComponent', :path => '../'
  pod 'AFNetworking','~>3.0.0'
  pod 'RTRootNavigationController'
  target 'BQBaseComponent_Tests' do
    inherit! :search_paths

    
  end
end
